(function(){
  function getSlides(){return Array.prototype.slice.call(document.querySelectorAll('.slide'));}
  function show(index){var slides=getSlides();slides.forEach(function(s,i){s.classList.toggle('active',i===index);});}
  function prepare(doc){doc.querySelectorAll('.photo,.side-img,.s2-image,.bottom-photo').forEach(function(img){var cs=doc.defaultView.getComputedStyle(img),bg=doc.createElement('div');bg.style.position=cs.position;bg.style.inset=cs.inset;bg.style.left=cs.left;bg.style.top=cs.top;bg.style.right=cs.right;bg.style.bottom=cs.bottom;bg.style.width=cs.width;bg.style.height=cs.height;bg.style.margin=cs.margin;bg.style.flex=cs.flex;bg.style.zIndex=cs.zIndex;bg.style.backgroundImage='url("'+(img.currentSrc||img.src)+'")';bg.style.backgroundSize='cover';bg.style.backgroundPosition=cs.objectPosition;bg.style.backgroundRepeat='no-repeat';img.parentNode.insertBefore(bg,img);img.style.visibility='hidden';});}
  function capture(slide){return window.html2canvas(slide,{scale:1080/420,width:420,height:525,useCORS:true,allowTaint:false,backgroundColor:null,onclone:prepare,logging:false});}
  async function exportPng(){var slides=getSlides(),active=slides.findIndex(function(s){return s.classList.contains('active');});for(var i=0;i<slides.length;i++){show(i);await new Promise(function(r){setTimeout(r,200);});var canvas=await capture(slides[i]),a=document.createElement('a');a.download='chatgpt-ads-'+String(i+1).padStart(2,'0')+'.png';a.href=canvas.toDataURL('image/png');a.click();}show(Math.max(active,0));}
  async function exportPdf(){if(!window.jspdf){alert('A biblioteca de PDF ainda está carregando. Tente novamente em instantes.');return;}var slides=getSlides(),active=slides.findIndex(function(s){return s.classList.contains('active');}),PDF=window.jspdf.jsPDF,pdf=new PDF({orientation:'portrait',unit:'px',format:[420,525],hotfixes:['px_scaling']});for(var i=0;i<slides.length;i++){show(i);await new Promise(function(r){setTimeout(r,200);});var canvas=await capture(slides[i]);if(i){pdf.addPage([420,525],'portrait');}pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,420,525);}show(Math.max(active,0));pdf.save('chatgpt-ads-expansao.pdf');}
  function loadPdf(){var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';document.head.appendChild(s);}
  window.addEventListener('DOMContentLoaded',function(){var controls=document.querySelector('.controls');if(!controls){return;}var btn=document.createElement('button');btn.className='secondary';btn.type='button';btn.textContent='↓ EXPORTAR PDF';btn.addEventListener('click',exportPdf);controls.appendChild(btn);window.exportAll=exportPng;loadPdf();});
})();